# Generated by Django 3.1.12 on 2024-11-20 17:39

from django.db import migrations, models
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        # Add a JSONField to store department members
        migrations.AddField(
            model_name='department',
            name='members',
            field=djongo.models.fields.JSONField(default=list),
        ),

        # Add fields to the Task model
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='subtasks',
            field=djongo.models.fields.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
