# Generated by Django 3.1.12 on 2024-11-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20241120_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='members',
        ),
        migrations.RemoveField(
            model_name='task',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='personal',
        ),
        migrations.RemoveField(
            model_name='task',
            name='subtasks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
