# Generated by Django 3.1.12 on 2024-11-30 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tasks', '0008_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.department'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_department_task',
            field=models.BooleanField(default=False),
        ),
    ]
