# Generated by Django 3.1.12 on 2024-12-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_notification'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='tasks_notif_user_id_9ee72a_idx'),
        ),
    ]
