# Generated by Django 3.1.12 on 2024-12-16 02:55

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20241211_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='changes',
            field=djongo.models.fields.JSONField(blank=True, null=True),
        ),
    ]
